version: 1.4.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
nuget:
  project_feed: true
before_build:
- ps: nuget restore
build:
  verbosity: minimal
artifacts:
- path: build